frase = input('Digite o seu nome completo: ')
print(frase.upper())
print(frase.lower())
a = frase.count('a')
b = frase.count('b')
c = frase.count('c')
d = frase.count('d')
e = frase.count('e')
f = frase.count('f')
g = frase.count('g')
h = frase.count('h')
i = frase.count('i')
j = frase.count('j')
k = frase.count('k')
l = frase.count('l')
m = frase.count('m')
n = frase.count('n')
o = frase.count('o')
p = frase.count('p')
q = frase.count('q')
r = frase.count('r')
s = frase.count('s')
t = frase.count('t')
u = frase.count('u')
v = frase.count('v')
w = frase.count('w')
x = frase.count('x')
y = frase.count('y')
z = frase.count('z')

A = frase.count('A')
B = frase.count('B')
C = frase.count('C')
D = frase.count('D')
E = frase.count('E')
F = frase.count('F')
G = frase.count('G')
H = frase.count('H')
I = frase.count('I')
J = frase.count('J')
K = frase.count('K')
L = frase.count('L')
M = frase.count('M')
N = frase.count('N')
O = frase.count('O')
P = frase.count('P')
Q = frase.count('Q')
R = frase.count('R')
S = frase.count('S')
T = frase.count('T')
U = frase.count('U')
V = frase.count('V')
W = frase.count('W')
X = frase.count('X')
Y = frase.count('Y')
Z = frase.count('Z')
z1 = (a + b + c + d + e + f + g + h + i + j + k + l + m
      + n + o + p + q + r + s + t + u + v + w + x + y + z)
z2 = (A + B + C + D + E + F + G + H + I + J + K + L + M
      + N + O + P + Q + R + S + T + U + V + W + X + Y + Z)
z3 = z1 + z2
print('Número de letras sem considerar espaços: ', z3)
dividido = frase.split()
print('Número de letras do primeiro nome: ', len(dividido[0]))
