n = int(input('Digite um valor: '))
n0 = 0 * n
n1 = 1 * n
n2 = 2 * n
n3 = 3 * n
n4 = 4 * n
n5 = 5 * n
n6 = 6 * n
n7 = 7 * n
n8 = 8 * n
n9 = 9 * n
n10 = 10 * n
print ('0 X {} = {}'.format(n, n0))
print ('1 X {} = {}'.format(n, n1))
print ('2 X {} = {}'.format(n, n2))
print ('3 X {} = {}'.format(n, n3))
print ('4 X {} = {}'.format(n, n4))
print ('5 X {} = {}'.format(n, n5))
print ('6 X {} = {}'.format(n, n6))
print ('7 X {} = {}'.format(n, n7))
print ('8 X {} = {}'.format(n, n8))
print ('9 X {} = {}'.format(n, n9))
print ('10 X {} = {}'.format(n, n10))